const express = require('express')
const cors = require('cors')
const conexao = require('./conexao')
conexao()
const rota = require('./Rotas')
const app = express()
app.use(rota)
app.use(cors())
app.listen('4000')